package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/takl/takl/internal/config"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize TAKL repository",
	Long: `Initialize a TAKL repository in the current directory.

This will create the necessary directory structure and configuration
files based on the detected mode (standalone or embedded).`,
	RunE: initRepository,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func initRepository(cmd *cobra.Command, args []string) error {
	mode, err := config.DetectMode(repoPath)
	if err != nil {
		return fmt.Errorf("failed to detect mode: %w", err)
	}

	cfg := &config.Config{Mode: mode}
	issuesDir := cfg.GetIssuesDir(repoPath)

	// Create issues directory
	if err := os.MkdirAll(issuesDir, 0755); err != nil {
		return fmt.Errorf("failed to create issues directory: %w", err)
	}

	// Create config file path
	var configPath string
	switch mode {
	case config.ModeEmbedded:
		configPath = filepath.Join(repoPath, ".takl", "config.yaml")
		if err := os.MkdirAll(filepath.Join(repoPath, ".takl"), 0755); err != nil {
			return fmt.Errorf("failed to create .takl directory: %w", err)
		}
	case config.ModeStandalone:
		configPath = filepath.Join(repoPath, "config.yaml")
	}

	// Create basic config if it doesn't exist
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		// Get project name from directory
		projectName := filepath.Base(repoPath)
		if projectName == "." || projectName == "/" {
			if wd, err := os.Getwd(); err == nil {
				projectName = filepath.Base(wd)
			} else {
				projectName = "My Project"
			}
		}

		configContent := fmt.Sprintf(`# TAKL Configuration
# Generated by takl init

project:
  name: %s

paradigm:
  id: kanban
  options:
    wip_limits:
      doing: 3
      review: 2

ui:
  date_format: "2006-01-02 15:04"

notifications:
  enabled: false

git:
  auto_commit: true
  commit_message: "Update issue: %%s"

# Legacy fields (deprecated but supported for backward compatibility)
mode: %s
web_port: 3000
`, projectName, mode)

		if err := os.WriteFile(configPath, []byte(configContent), 0644); err != nil {
			return fmt.Errorf("failed to create config file: %w", err)
		}
	}

	fmt.Printf("Initialized TAKL repository in %s mode\n", mode)
	fmt.Printf("Issues directory: %s\n", issuesDir)
	fmt.Printf("Config file: %s\n", configPath)

	return nil
}
