#!/bin/bash

# TAKL Codebase Documentation Generator
# Generates a comprehensive markdown document describing the entire codebase

set -e

OUTPUT_FILE="${1:-codebase-description.md}"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "Generating codebase description..."
echo "Project root: $PROJECT_ROOT"
echo "Output file: $OUTPUT_FILE"

cd "$PROJECT_ROOT"

# Create temporary file 
TEMP_FILE="$(mktemp)"
trap "rm -f $TEMP_FILE" EXIT

# Start the markdown document
{
echo "# TAKL Codebase Documentation"
echo ""
echo "This document provides a complete overview of the TAKL (git-native issue tracker) codebase."
echo ""
echo "**Generated on:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo ""
echo "## Project Overview"
echo ""
echo "TAKL is a git-native issue tracker that embeds issue management directly into your repository structure. It features a daemon-based architecture with Unix socket communication and comprehensive project registry management."
echo ""
echo "## Directory Structure"
echo ""
echo '```'
} > "$TEMP_FILE"

# Create tree structure (excluding hidden files, node_modules, vendor, etc.)
if command -v tree >/dev/null 2>&1; then
    tree -a -I '.git|.vscode|.idea|node_modules|vendor|*.log|*.tmp|*.swp|coverage.*|*.test|*.out|bin' >> "$TEMP_FILE" 2>/dev/null || {
        find . -type d \( -name '.git' -o -name '.vscode' -o -name '.idea' -o -name 'node_modules' -o -name 'vendor' \) -prune -o -type f -print | sort >> "$TEMP_FILE"
    }
else
    find . -type d \( -name '.git' -o -name '.vscode' -o -name '.idea' -o -name 'node_modules' -o -name 'vendor' \) -prune -o -type f -print | sort >> "$TEMP_FILE"
fi

{
echo '```'
echo ""
echo "## File Contents"
echo ""
} >> "$TEMP_FILE"

# Get all files to include (excluding binary, generated, and temporary files)
find . -type f \( \
    -name '*.go' -o \
    -name '*.md' -o \
    -name '*.yaml' -o \
    -name '*.yml' -o \
    -name '*.json' -o \
    -name '*.toml' -o \
    -name '*.txt' -o \
    -name '*.sh' -o \
    -name '*.service' -o \
    -name '*.plist' -o \
    -name 'Makefile' -o \
    -name 'Dockerfile' -o \
    -name 'go.mod' -o \
    -name 'go.sum' -o \
    -name '.gitignore' -o \
    -name 'LICENSE' \
\) \
    ! -path 'web/pnpm-lock.yaml' \
    ! -path './.git/*' \
    ! -path './.vscode/*' \
    ! -path './.idea/*' \
    ! -path './vendor/*' \
    ! -path './node_modules/*' \
    ! -name '*.test' \
    ! -name '*.out' \
    ! -name 'coverage.*' \
    ! -name 'codebase-description.md' \
    | sort | while read -r file; do
    
    # Skip if file doesn't exist or is not readable
    [[ ! -r "$file" ]] && continue
    
    # Get relative path from project root
    rel_path="${file#./}"
    
    # Skip if file is too large (>100KB)
    file_size=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file" 2>/dev/null || echo 0)
    if [[ $file_size -gt 102400 ]]; then
        {
        echo "### \`$rel_path\`"
        echo ""
        echo "_File too large (>100KB) - skipped_"
        echo ""
        } >> "$TEMP_FILE"
        continue
    fi
    
    # Determine file type for syntax highlighting
    ext="${file##*.}"
    case "$ext" in
        go) lang="go" ;;
        md) lang="markdown" ;;
        yaml|yml) lang="yaml" ;;
        json) lang="json" ;;
        sh) lang="bash" ;;
        toml) lang="toml" ;;
        service) lang="ini" ;;
        plist) lang="xml" ;;
        *) lang="text" ;;
    esac
    
    # Add file header and content
    {
    echo "### \`$rel_path\`"
    echo ""
    echo '```'$lang
    cat "$file"
    echo '```'
    echo ""
    } >> "$TEMP_FILE"
    
    echo "  ✓ Added: $rel_path"
done

# Add summary statistics
{
echo "## Project Statistics"
echo ""
} >> "$TEMP_FILE"

# Count files by type
go_files=$(find . -name '*.go' ! -path './.git/*' | wc -l)
test_files=$(find . -name '*_test.go' ! -path './.git/*' | wc -l)
md_files=$(find . -name '*.md' ! -path './.git/*' | wc -l)
total_files=$(find . -type f ! -path './.git/*' ! -path './.vscode/*' ! -path './.idea/*' | wc -l)

{
echo "- **Total files:** $total_files"
echo "- **Go files:** $go_files"
echo "- **Test files:** $test_files"
echo "- **Documentation files:** $md_files"
echo ""
} >> "$TEMP_FILE"

# Count lines of code
if command -v cloc >/dev/null 2>&1; then
    {
    echo "## Code Statistics (via cloc)"
    echo ""
    echo '```'
    cloc --exclude-dir=.git,.vscode,.idea,vendor,node_modules .
    echo '```'
    } >> "$TEMP_FILE"
else
    total_lines=$(find . -name '*.go' ! -path './.git/*' -exec wc -l {} + 2>/dev/null | tail -n1 | awk '{print $1}' || echo "0")
    {
    echo "## Lines of Code"
    echo ""
    echo "- **Go code lines:** $total_lines"
    } >> "$TEMP_FILE"
fi

{
echo ""
echo "---"
echo "*Generated by \`scripts/describe-codebase.sh\` on $(date -u +"%Y-%m-%d %H:%M:%S UTC")*"
} >> "$TEMP_FILE"

# Move temp file to final location
mv "$TEMP_FILE" "$OUTPUT_FILE"

echo ""
echo "✅ Codebase description generated: $OUTPUT_FILE"
echo "📊 Files processed: $(find . -type f \( -name '*.go' -o -name '*.md' -o -name '*.yaml' -o -name '*.yml' -o -name '*.json' \) ! -path './.git/*' | wc -l)"
